### ISSUE TITLE
Error occurs when using Properties item in context menu item from InteractiveChart of SWT chart extension

### ISSUE THREAD

**Issue by QuocDoBV** [eclipse/swtchart#419]
I have created a java project which uses an InteractiveChart from SWT chart extension. Then using context menu of the chart. 
The exception as below throws when trying to open Properties item in the second time.
```
Exception in thread "main" java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.setForeground(GC.java:4409)
	at org.eclipse.swtchart.internal.Title.paintControl(Title.java:294)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1536)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4801)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5039)
	at org.eclipse.swt.internal.win32.OS.RedrawWindow(Native Method)
	at org.eclipse.swt.widgets.Control.update(Control.java:4588)
	at org.eclipse.swt.widgets.Display.update(Display.java:5009)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:830)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.swtchart.extensions.charts.InteractiveChart.openPropertiesDialog(InteractiveChart.java:488)
	at org.eclipse.swtchart.extensions.charts.InteractiveChart.handleSelectionEvent(InteractiveChart.java:409)
	at org.eclipse.swtchart.extensions.charts.InteractiveChart.handleEvent(InteractiveChart.java:202)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at Test.main(Test.java:42)
```
**How to reproduce**:
1. Create a plug-in project with below settings:
![image](https://github.com/user-attachments/assets/adc92d07-1206-4032-8263-c513d713e668)
2. Create main source with as attached file
[Test.txt](https://github.com/user-attachments/files/17485615/Test.txt)
3. Run the source
4. Right-click on the chart to open Properties dialog. Then clicking **Close and Apply** button to close the dialog and apply settings
![image](https://github.com/user-attachments/assets/a173d52d-93fa-4e85-8472-7792fdf266a9)
5. Repeat step 4
**Expected**: Can change settings on Propeties dialog
**Actual**: Exception throws.
**Note**: the problem only happen when i using SWT extension. If I import SWT source to my workspace then using them the problem does not happen

**Comment by QuocDoBV** [comment]
Hi @eselmeister,
Could you please take a look at this?
Thank you!

**Comment by eselmeister** [comment]
Sure, I will have a look at it.

**Comment by eselmeister** [comment]
![Screenshot From 2024-10-25 10-12-32](https://github.com/user-attachments/assets/46954115-b4d4-4e74-bcbe-317d2917a373)
![Screenshot From 2024-10-25 10-12-38](https://github.com/user-attachments/assets/5073fbfb-08c0-482b-b04d-97e2b9d42b00)

**Comment by QuocDoBV** [comment]
Hi @eselmeister,
The problem still occurs. 
![image](https://github.com/user-attachments/assets/e35b9d68-1f3c-4cff-b903-a92a18c178c9)
Let close all projects in your workspace to make sure that the application is using extension instead of library from projects in your workspace.  The extension is used from https://download.eclipse.org/swtchart/releases/0.14.0/

**Comment by QuocDoBV** [comment]
The problem only occurs the second time I open the Properties dialog.
